//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans;

import java.math.BigInteger;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A SRA analysis object captures sequence analysis results including sequence alignments, sequence variations and sequence annotations.
 *             
 * 
 * <p>Java class for AnalysisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalysisType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *         &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STUDY_REF" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SAMPLE_REF" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EXPERIMENT_REF" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RUN_REF" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ANALYSIS_REF" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{SRA.common}RefNameGroup"/>
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ANALYSIS_TYPE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="REFERENCE_ALIGNMENT" type="{SRA.common}ReferenceSequenceType"/>
 *                   &lt;element name="SEQUENCE_VARIATION">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{SRA.common}ReferenceSequenceType">
 *                           &lt;sequence>
 *                             &lt;element name="EXPERIMENT_TYPE" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="Whole genome sequencing"/>
 *                                   &lt;enumeration value="Exome sequencing"/>
 *                                   &lt;enumeration value="Genotyping by array"/>
 *                                   &lt;enumeration value="transcriptomics"/>
 *                                   &lt;enumeration value="Curation"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="IMPUTATION" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SEQUENCE_ASSEMBLY">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PARTIAL" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="COVERAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MIN_GAP_LENGTH" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="MOL_TYPE" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="genomic DNA"/>
 *                                   &lt;enumeration value="genomic RNA"/>
 *                                   &lt;enumeration value="viral cRNA"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SEQUENCE_ANNOTATION">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="REFERENCE_SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="SAMPLE_PHENOTYPE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PROCESSED_READS" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;sequence>
 *           &lt;element name="FILES">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="FILE" type="{}AnalysisFileType" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="ANALYSIS_LINKS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="ANALYSIS_LINK" type="{SRA.common}LinkType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ANALYSIS_ATTRIBUTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="ANALYSIS_ATTRIBUTE" type="{SRA.common}AttributeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{SRA.common}NameGroup"/>
 *       &lt;attribute name="analysis_center" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="analysis_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ANALYSIS {


    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    IdentifierType getIDENTIFIERS();

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    void setIDENTIFIERS(IdentifierType value);

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getTITLE();

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setTITLE(String value);

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getDESCRIPTION();

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setDESCRIPTION(String value);

    /**
     * Gets the value of the studyref property.
     * 
     * @return
     *     possible object is
     *     {@link ANALYSIS.STUDYREF }
     *     
     */
    ANALYSIS.STUDYREF getSTUDYREF();

    /**
     * Sets the value of the studyref property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANALYSIS.STUDYREF }
     *     
     */
    void setSTUDYREF(ANALYSIS.STUDYREF value);

    /**
     * Gets the value of the samplereves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samplereves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAMPLEREVES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ANALYSIS.SAMPLEREF }
     * 
     * 
     */
    List<ANALYSIS.SAMPLEREF> getSAMPLEREVES();

    /**
     * Gets the value of the experimentreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXPERIMENTREVES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ANALYSIS.EXPERIMENTREF }
     * 
     * 
     */
    List<ANALYSIS.EXPERIMENTREF> getEXPERIMENTREVES();

    /**
     * Gets the value of the runreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRUNREVES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ANALYSIS.RUNREF }
     * 
     * 
     */
    List<ANALYSIS.RUNREF> getRUNREVES();

    /**
     * Gets the value of the analysisreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analysisreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getANALYSISREVES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ANALYSIS.ANALYSISREF }
     * 
     * 
     */
    List<ANALYSIS.ANALYSISREF> getANALYSISREVES();

    /**
     * Gets the value of the analysistype property.
     * 
     * @return
     *     possible object is
     *     {@link ANALYSIS.ANALYSISTYPE }
     *     
     */
    ANALYSIS.ANALYSISTYPE getANALYSISTYPE();

    /**
     * Sets the value of the analysistype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANALYSIS.ANALYSISTYPE }
     *     
     */
    void setANALYSISTYPE(ANALYSIS.ANALYSISTYPE value);

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link ANALYSIS.FILES }
     *     
     */
    ANALYSIS.FILES getFILES();

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANALYSIS.FILES }
     *     
     */
    void setFILES(ANALYSIS.FILES value);

    /**
     * Gets the value of the analysislinks property.
     * 
     * @return
     *     possible object is
     *     {@link ANALYSIS.ANALYSISLINKS }
     *     
     */
    ANALYSIS.ANALYSISLINKS getANALYSISLINKS();

    /**
     * Sets the value of the analysislinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANALYSIS.ANALYSISLINKS }
     *     
     */
    void setANALYSISLINKS(ANALYSIS.ANALYSISLINKS value);

    /**
     * Gets the value of the analysisattributes property.
     * 
     * @return
     *     possible object is
     *     {@link ANALYSIS.ANALYSISATTRIBUTES }
     *     
     */
    ANALYSIS.ANALYSISATTRIBUTES getANALYSISATTRIBUTES();

    /**
     * Sets the value of the analysisattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANALYSIS.ANALYSISATTRIBUTES }
     *     
     */
    void setANALYSISATTRIBUTES(ANALYSIS.ANALYSISATTRIBUTES value);

    /**
     * Gets the value of the analysisCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getAnalysisCenter();

    /**
     * Sets the value of the analysisCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setAnalysisCenter(String value);

    /**
     * Gets the value of the analysisDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    XMLGregorianCalendar getAnalysisDate();

    /**
     * Sets the value of the analysisDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    void setAnalysisDate(XMLGregorianCalendar value);

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getAlias();

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setAlias(String value);

    /**
     * Gets the value of the centerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getCenterName();

    /**
     * Sets the value of the centerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setCenterName(String value);

    /**
     * Gets the value of the brokerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getBrokerName();

    /**
     * Sets the value of the brokerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setBrokerName(String value);

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    String getAccession();

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    void setAccession(String value);


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="ANALYSIS_ATTRIBUTE" type="{SRA.common}AttributeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface ANALYSISATTRIBUTES {


        /**
         * Gets the value of the analysisattributes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the analysisattributes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getANALYSISATTRIBUTES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttributeType }
         * 
         * 
         */
        List<AttributeType> getANALYSISATTRIBUTES();

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="ANALYSIS_LINK" type="{SRA.common}LinkType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface ANALYSISLINKS {


        /**
         * Gets the value of the analysislinks property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the analysislinks property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getANALYSISLINKS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LinkType }
         * 
         * 
         */
        List<LinkType> getANALYSISLINKS();

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface ANALYSISREF {


        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        IdentifierType getIDENTIFIERS();

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        void setIDENTIFIERS(IdentifierType value);

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getLabel();

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setLabel(String value);

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefname();

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefname(String value);

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefcenter();

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefcenter(String value);

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getAccession();

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setAccession(String value);

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="REFERENCE_ALIGNMENT" type="{SRA.common}ReferenceSequenceType"/>
     *         &lt;element name="SEQUENCE_VARIATION">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{SRA.common}ReferenceSequenceType">
     *                 &lt;sequence>
     *                   &lt;element name="EXPERIMENT_TYPE" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="Whole genome sequencing"/>
     *                         &lt;enumeration value="Exome sequencing"/>
     *                         &lt;enumeration value="Genotyping by array"/>
     *                         &lt;enumeration value="transcriptomics"/>
     *                         &lt;enumeration value="Curation"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="IMPUTATION" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SEQUENCE_ASSEMBLY">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PARTIAL" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="COVERAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MIN_GAP_LENGTH" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="MOL_TYPE" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="genomic DNA"/>
     *                         &lt;enumeration value="genomic RNA"/>
     *                         &lt;enumeration value="viral cRNA"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SEQUENCE_ANNOTATION">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="REFERENCE_SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="SAMPLE_PHENOTYPE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PROCESSED_READS" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface ANALYSISTYPE {


        /**
         * Gets the value of the processedreads property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        Object getPROCESSEDREADS();

        /**
         * Sets the value of the processedreads property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        void setPROCESSEDREADS(Object value);

        /**
         * Gets the value of the samplephenotype property.
         * 
         * @return
         *     possible object is
         *     {@link ANALYSIS.ANALYSISTYPE.SAMPLEPHENOTYPE }
         *     
         */
        ANALYSIS.ANALYSISTYPE.SAMPLEPHENOTYPE getSAMPLEPHENOTYPE();

        /**
         * Sets the value of the samplephenotype property.
         * 
         * @param value
         *     allowed object is
         *     {@link ANALYSIS.ANALYSISTYPE.SAMPLEPHENOTYPE }
         *     
         */
        void setSAMPLEPHENOTYPE(ANALYSIS.ANALYSISTYPE.SAMPLEPHENOTYPE value);

        /**
         * Gets the value of the referencesequence property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        Object getREFERENCESEQUENCE();

        /**
         * Sets the value of the referencesequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        void setREFERENCESEQUENCE(Object value);

        /**
         * Gets the value of the sequenceannotation property.
         * 
         * @return
         *     possible object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEANNOTATION }
         *     
         */
        ANALYSIS.ANALYSISTYPE.SEQUENCEANNOTATION getSEQUENCEANNOTATION();

        /**
         * Sets the value of the sequenceannotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEANNOTATION }
         *     
         */
        void setSEQUENCEANNOTATION(ANALYSIS.ANALYSISTYPE.SEQUENCEANNOTATION value);

        /**
         * Gets the value of the sequenceassembly property.
         * 
         * @return
         *     possible object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEASSEMBLY }
         *     
         */
        ANALYSIS.ANALYSISTYPE.SEQUENCEASSEMBLY getSEQUENCEASSEMBLY();

        /**
         * Sets the value of the sequenceassembly property.
         * 
         * @param value
         *     allowed object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEASSEMBLY }
         *     
         */
        void setSEQUENCEASSEMBLY(ANALYSIS.ANALYSISTYPE.SEQUENCEASSEMBLY value);

        /**
         * Gets the value of the sequencevariation property.
         * 
         * @return
         *     possible object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEVARIATION }
         *     
         */
        ANALYSIS.ANALYSISTYPE.SEQUENCEVARIATION getSEQUENCEVARIATION();

        /**
         * Sets the value of the sequencevariation property.
         * 
         * @param value
         *     allowed object is
         *     {@link ANALYSIS.ANALYSISTYPE.SEQUENCEVARIATION }
         *     
         */
        void setSEQUENCEVARIATION(ANALYSIS.ANALYSISTYPE.SEQUENCEVARIATION value);

        /**
         * Gets the value of the referencealignment property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceSequenceType }
         *     
         */
        ReferenceSequenceType getREFERENCEALIGNMENT();

        /**
         * Sets the value of the referencealignment property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceSequenceType }
         *     
         */
        void setREFERENCEALIGNMENT(ReferenceSequenceType value);


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public interface SAMPLEPHENOTYPE {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public interface SEQUENCEANNOTATION {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PARTIAL" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="COVERAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MIN_GAP_LENGTH" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="MOL_TYPE" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="genomic DNA"/>
         *               &lt;enumeration value="genomic RNA"/>
         *               &lt;enumeration value="viral cRNA"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public interface SEQUENCEASSEMBLY {


            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getNAME();

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setNAME(String value);

            /**
             * Gets the value of the partial property.
             * 
             */
            boolean isPARTIAL();

            /**
             * Sets the value of the partial property.
             * 
             */
            void setPARTIAL(boolean value);

            /**
             * Gets the value of the coverage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getCOVERAGE();

            /**
             * Sets the value of the coverage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setCOVERAGE(String value);

            /**
             * Gets the value of the program property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getPROGRAM();

            /**
             * Sets the value of the program property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setPROGRAM(String value);

            /**
             * Gets the value of the platform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getPLATFORM();

            /**
             * Sets the value of the platform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setPLATFORM(String value);

            /**
             * Gets the value of the mingaplength property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            BigInteger getMINGAPLENGTH();

            /**
             * Sets the value of the mingaplength property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            void setMINGAPLENGTH(BigInteger value);

            /**
             * Gets the value of the moltype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getMOLTYPE();

            /**
             * Sets the value of the moltype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setMOLTYPE(String value);

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{SRA.common}ReferenceSequenceType">
         *       &lt;sequence>
         *         &lt;element name="EXPERIMENT_TYPE" maxOccurs="unbounded" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="Whole genome sequencing"/>
         *               &lt;enumeration value="Exome sequencing"/>
         *               &lt;enumeration value="Genotyping by array"/>
         *               &lt;enumeration value="transcriptomics"/>
         *               &lt;enumeration value="Curation"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="PROGRAM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="IMPUTATION" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public interface SEQUENCEVARIATION
            extends ReferenceSequenceType
        {


            /**
             * Gets the value of the experimenttypes property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the experimenttypes property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEXPERIMENTTYPES().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            List<String> getEXPERIMENTTYPES();

            /**
             * Gets the value of the program property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getPROGRAM();

            /**
             * Sets the value of the program property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setPROGRAM(String value);

            /**
             * Gets the value of the platform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            String getPLATFORM();

            /**
             * Sets the value of the platform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            void setPLATFORM(String value);

            /**
             * Gets the value of the imputation property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            Boolean isIMPUTATION();

            /**
             * Sets the value of the imputation property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            void setIMPUTATION(Boolean value);

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface EXPERIMENTREF {


        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        IdentifierType getIDENTIFIERS();

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        void setIDENTIFIERS(IdentifierType value);

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefname();

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefname(String value);

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefcenter();

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefcenter(String value);

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getAccession();

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setAccession(String value);

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FILE" type="{}AnalysisFileType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface FILES {


        /**
         * Gets the value of the files property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the files property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFILES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnalysisFileType }
         * 
         * 
         */
        List<AnalysisFileType> getFILES();

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface RUNREF {


        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        IdentifierType getIDENTIFIERS();

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        void setIDENTIFIERS(IdentifierType value);

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getLabel();

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setLabel(String value);

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefname();

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefname(String value);

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefcenter();

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefcenter(String value);

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getAccession();

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setAccession(String value);

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface SAMPLEREF {


        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        IdentifierType getIDENTIFIERS();

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        void setIDENTIFIERS(IdentifierType value);

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getLabel();

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setLabel(String value);

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefname();

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefname(String value);

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefcenter();

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefcenter(String value);

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getAccession();

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setAccession(String value);

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDENTIFIERS" type="{SRA.common}IdentifierType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{SRA.common}RefNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public interface STUDYREF {


        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        IdentifierType getIDENTIFIERS();

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        void setIDENTIFIERS(IdentifierType value);

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefname();

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefname(String value);

        /**
         * Gets the value of the refcenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getRefcenter();

        /**
         * Sets the value of the refcenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setRefcenter(String value);

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        String getAccession();

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        void setAccession(String value);

    }

}
