//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans;



/**
 * <p>Java class for ProcessingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PIPELINE" type="{SRA.common}PipelineType" minOccurs="0"/>
 *         &lt;element name="DIRECTIVES" type="{SRA.common}SequencingDirectivesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ProcessingType {


    /**
     * Gets the value of the pipeline property.
     * 
     * @return
     *     possible object is
     *     {@link PipelineType }
     *     
     */
    PipelineType getPIPELINE();

    /**
     * Sets the value of the pipeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link PipelineType }
     *     
     */
    void setPIPELINE(PipelineType value);

    /**
     * Gets the value of the directives property.
     * 
     * @return
     *     possible object is
     *     {@link SequencingDirectivesType }
     *     
     */
    SequencingDirectivesType getDIRECTIVES();

    /**
     * Sets the value of the directives property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencingDirectivesType }
     *     
     */
    void setDIRECTIVES(SequencingDirectivesType value);

}
