//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 11:50:41 AM GMT 
//


package uk.ac.ebi.literature.data_citation.common.jats;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}journal-meta-model"/>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalIds",
    "journalTitleGroups",
    "contribGroupsAndAfvesAndAffAlternatives",
    "issns",
    "issnL",
    "isbns",
    "publisher",
    "notes",
    "selfUris",
    "customMetaGroup"
})
@XmlRootElement(name = "journal-meta")
public class JournalMeta {

    @XmlElement(name = "journal-id")
    protected List<JournalId> journalIds;
    @XmlElement(name = "journal-title-group")
    protected List<JournalTitleGroup> journalTitleGroups;
    @XmlElements({
        @XmlElement(name = "contrib-group", type = ContribGroup.class),
        @XmlElement(name = "aff", type = Aff.class),
        @XmlElement(name = "aff-alternatives", type = AffAlternatives.class)
    })
    protected List<Object> contribGroupsAndAfvesAndAffAlternatives;
    @XmlElement(name = "issn")
    protected List<Issn> issns;
    @XmlElement(name = "issn-l")
    protected IssnL issnL;
    @XmlElement(name = "isbn")
    protected List<Isbn> isbns;
    protected Publisher publisher;
    protected List<Notes> notes;
    @XmlElement(name = "self-uri")
    protected List<SelfUri> selfUris;
    @XmlElement(name = "custom-meta-group")
    protected CustomMetaGroup customMetaGroup;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * Gets the value of the journalIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalId }
     * 
     * 
     */
    public List<JournalId> getJournalIds() {
        if (journalIds == null) {
            journalIds = new ArrayList<JournalId>();
        }
        return this.journalIds;
    }

    /**
     * Gets the value of the journalTitleGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalTitleGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalTitleGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalTitleGroup }
     * 
     * 
     */
    public List<JournalTitleGroup> getJournalTitleGroups() {
        if (journalTitleGroups == null) {
            journalTitleGroups = new ArrayList<JournalTitleGroup>();
        }
        return this.journalTitleGroups;
    }

    /**
     * Gets the value of the contribGroupsAndAfvesAndAffAlternatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contribGroupsAndAfvesAndAffAlternatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContribGroupsAndAfvesAndAffAlternatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContribGroup }
     * {@link Aff }
     * {@link AffAlternatives }
     * 
     * 
     */
    public List<Object> getContribGroupsAndAfvesAndAffAlternatives() {
        if (contribGroupsAndAfvesAndAffAlternatives == null) {
            contribGroupsAndAfvesAndAffAlternatives = new ArrayList<Object>();
        }
        return this.contribGroupsAndAfvesAndAffAlternatives;
    }

    /**
     * Gets the value of the issns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Issn }
     * 
     * 
     */
    public List<Issn> getIssns() {
        if (issns == null) {
            issns = new ArrayList<Issn>();
        }
        return this.issns;
    }

    /**
     * Gets the value of the issnL property.
     * 
     * @return
     *     possible object is
     *     {@link IssnL }
     *     
     */
    public IssnL getIssnL() {
        return issnL;
    }

    /**
     * Sets the value of the issnL property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssnL }
     *     
     */
    public void setIssnL(IssnL value) {
        this.issnL = value;
    }

    /**
     * Gets the value of the isbns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsbns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Isbn }
     * 
     * 
     */
    public List<Isbn> getIsbns() {
        if (isbns == null) {
            isbns = new ArrayList<Isbn>();
        }
        return this.isbns;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notes }
     * 
     * 
     */
    public List<Notes> getNotes() {
        if (notes == null) {
            notes = new ArrayList<Notes>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the selfUris property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfUris property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfUris().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelfUri }
     * 
     * 
     */
    public List<SelfUri> getSelfUris() {
        if (selfUris == null) {
            selfUris = new ArrayList<SelfUri>();
        }
        return this.selfUris;
    }

    /**
     * Gets the value of the customMetaGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CustomMetaGroup }
     *     
     */
    public CustomMetaGroup getCustomMetaGroup() {
        return customMetaGroup;
    }

    /**
     * Sets the value of the customMetaGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomMetaGroup }
     *     
     */
    public void setCustomMetaGroup(CustomMetaGroup value) {
        this.customMetaGroup = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
