//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Entry;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.XrefType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntryType", propOrder = {
    "secondaryAccessions",
    "projectAccessions",
    "description",
    "comment",
    "keywords",
    "references",
    "xreves",
    "features",
    "assembly",
    "contig",
    "sequence"
})
@XmlRootElement(name = "entry")
public class EntryImpl implements Entry
{

    @XmlElement(name = "secondaryAccession")
    protected List<String> secondaryAccessions;
    @XmlElement(name = "projectAccession")
    protected List<String> projectAccessions;
    @XmlElement(required = true)
    protected String description;
    protected String comment;
    @XmlElement(name = "keyword")
    protected List<String> keywords;
    @XmlElement(name = "reference", type = EntryImpl.ReferenceImpl.class)
    protected List<Entry.Reference> references;
    @XmlElement(name = "xref", type = XrefTypeImpl.class)
    protected List<XrefType> xreves;
    @XmlElement(name = "feature", type = EntryImpl.FeatureImpl.class)
    protected List<Entry.Feature> features;
    @XmlElement(type = EntryImpl.AssemblyImpl.class)
    protected EntryImpl.AssemblyImpl assembly;
    @XmlElement(type = EntryImpl.ContigImpl.class)
    protected EntryImpl.ContigImpl contig;
    protected String sequence;
    @XmlAttribute(name = "accession", required = true)
    protected String accession;
    @XmlAttribute(name = "version", required = true)
    protected BigInteger version;
    @XmlAttribute(name = "entryVersion")
    protected BigInteger entryVersion;
    @XmlAttribute(name = "dataClass", required = true)
    protected String dataClass;
    @XmlAttribute(name = "taxonomicDivision", required = true)
    protected String taxonomicDivision;
    @XmlAttribute(name = "moleculeType", required = true)
    protected String moleculeType;
    @XmlAttribute(name = "sequenceLength", required = true)
    protected BigInteger sequenceLength;
    @XmlAttribute(name = "topology", required = true)
    protected String topology;
    @XmlAttribute(name = "firstPublic")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstPublic;
    @XmlAttribute(name = "firstPublicRelease")
    protected BigInteger firstPublicRelease;
    @XmlAttribute(name = "lastUpdated")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdated;
    @XmlAttribute(name = "lastUpdatedRelease")
    protected BigInteger lastUpdatedRelease;

    public List<String> getSecondaryAccessions() {
        if (secondaryAccessions == null) {
            secondaryAccessions = new ArrayList<String>();
        }
        return this.secondaryAccessions;
    }

    public List<String> getProjectAccessions() {
        if (projectAccessions == null) {
            projectAccessions = new ArrayList<String>();
        }
        return this.projectAccessions;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String value) {
        this.comment = value;
    }

    public List<String> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<String>();
        }
        return this.keywords;
    }

    public List<Entry.Reference> getReferences() {
        if (references == null) {
            references = new ArrayList<Entry.Reference>();
        }
        return this.references;
    }

    public List<XrefType> getXreves() {
        if (xreves == null) {
            xreves = new ArrayList<XrefType>();
        }
        return this.xreves;
    }

    public List<Entry.Feature> getFeatures() {
        if (features == null) {
            features = new ArrayList<Entry.Feature>();
        }
        return this.features;
    }

    public Entry.Assembly getAssembly() {
        return assembly;
    }

    public void setAssembly(Entry.Assembly value) {
        this.assembly = ((EntryImpl.AssemblyImpl) value);
    }

    public Entry.Contig getContig() {
        return contig;
    }

    public void setContig(Entry.Contig value) {
        this.contig = ((EntryImpl.ContigImpl) value);
    }

    public String getSequence() {
        return sequence;
    }

    public void setSequence(String value) {
        this.sequence = value;
    }

    public String getAccession() {
        return accession;
    }

    public void setAccession(String value) {
        this.accession = value;
    }

    public BigInteger getVersion() {
        return version;
    }

    public void setVersion(BigInteger value) {
        this.version = value;
    }

    public BigInteger getEntryVersion() {
        return entryVersion;
    }

    public void setEntryVersion(BigInteger value) {
        this.entryVersion = value;
    }

    public String getDataClass() {
        return dataClass;
    }

    public void setDataClass(String value) {
        this.dataClass = value;
    }

    public String getTaxonomicDivision() {
        return taxonomicDivision;
    }

    public void setTaxonomicDivision(String value) {
        this.taxonomicDivision = value;
    }

    public String getMoleculeType() {
        return moleculeType;
    }

    public void setMoleculeType(String value) {
        this.moleculeType = value;
    }

    public BigInteger getSequenceLength() {
        return sequenceLength;
    }

    public void setSequenceLength(BigInteger value) {
        this.sequenceLength = value;
    }

    public String getTopology() {
        return topology;
    }

    public void setTopology(String value) {
        this.topology = value;
    }

    public XMLGregorianCalendar getFirstPublic() {
        return firstPublic;
    }

    public void setFirstPublic(XMLGregorianCalendar value) {
        this.firstPublic = value;
    }

    public BigInteger getFirstPublicRelease() {
        return firstPublicRelease;
    }

    public void setFirstPublicRelease(BigInteger value) {
        this.firstPublicRelease = value;
    }

    public XMLGregorianCalendar getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(XMLGregorianCalendar value) {
        this.lastUpdated = value;
    }

    public BigInteger getLastUpdatedRelease() {
        return lastUpdatedRelease;
    }

    public void setLastUpdatedRelease(BigInteger value) {
        this.lastUpdatedRelease = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ranges"
    })
    public static class AssemblyImpl
        implements Entry.Assembly
    {

        @XmlElement(name = "range", required = true, type = EntryImpl.AssemblyImpl.RangeImpl.class)
        protected List<Entry.Assembly.Range> ranges;

        public List<Entry.Assembly.Range> getRanges() {
            if (ranges == null) {
                ranges = new ArrayList<Entry.Assembly.Range>();
            }
            return this.ranges;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RangeImpl
            implements Entry.Assembly.Range
        {

            @XmlAttribute(name = "begin", required = true)
            protected BigInteger begin;
            @XmlAttribute(name = "end", required = true)
            protected BigInteger end;
            @XmlAttribute(name = "primaryBegin")
            protected BigInteger primaryBegin;
            @XmlAttribute(name = "primaryEnd")
            protected BigInteger primaryEnd;
            @XmlAttribute(name = "accession", required = true)
            protected String accession;
            @XmlAttribute(name = "version", required = true)
            protected BigInteger version;
            @XmlAttribute(name = "complement")
            protected Boolean complement;

            public BigInteger getBegin() {
                return begin;
            }

            public void setBegin(BigInteger value) {
                this.begin = value;
            }

            public BigInteger getEnd() {
                return end;
            }

            public void setEnd(BigInteger value) {
                this.end = value;
            }

            public BigInteger getPrimaryBegin() {
                return primaryBegin;
            }

            public void setPrimaryBegin(BigInteger value) {
                this.primaryBegin = value;
            }

            public BigInteger getPrimaryEnd() {
                return primaryEnd;
            }

            public void setPrimaryEnd(BigInteger value) {
                this.primaryEnd = value;
            }

            public String getAccession() {
                return accession;
            }

            public void setAccession(String value) {
                this.accession = value;
            }

            public BigInteger getVersion() {
                return version;
            }

            public void setVersion(BigInteger value) {
                this.version = value;
            }

            public boolean isComplement() {
                if (complement == null) {
                    return false;
                } else {
                    return complement;
                }
            }

            public void setComplement(Boolean value) {
                this.complement = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rangesAndGaps"
    })
    public static class ContigImpl
        implements Entry.Contig
    {

        @XmlElements({
            @XmlElement(name = "range", type = EntryImpl.ContigImpl.RangeImpl.class),
            @XmlElement(name = "gap", type = EntryImpl.ContigImpl.GapImpl.class)
        })
        protected List<Object> rangesAndGaps;

        public List<Object> getRangesAndGaps() {
            if (rangesAndGaps == null) {
                rangesAndGaps = new ArrayList<Object>();
            }
            return this.rangesAndGaps;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GapImpl implements Entry.Contig.Gap
        {

            @XmlAttribute(name = "begin", required = true)
            protected BigInteger begin;
            @XmlAttribute(name = "end", required = true)
            protected BigInteger end;
            @XmlAttribute(name = "length", required = true)
            protected BigInteger length;
            @XmlAttribute(name = "unknownLength")
            protected Boolean unknownLength;

            public BigInteger getBegin() {
                return begin;
            }

            public void setBegin(BigInteger value) {
                this.begin = value;
            }

            public BigInteger getEnd() {
                return end;
            }

            public void setEnd(BigInteger value) {
                this.end = value;
            }

            public BigInteger getLength() {
                return length;
            }

            public void setLength(BigInteger value) {
                this.length = value;
            }

            public boolean isUnknownLength() {
                if (unknownLength == null) {
                    return false;
                } else {
                    return unknownLength;
                }
            }

            public void setUnknownLength(Boolean value) {
                this.unknownLength = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RangeImpl implements Entry.Contig.Range
        {

            @XmlAttribute(name = "begin", required = true)
            protected BigInteger begin;
            @XmlAttribute(name = "end", required = true)
            protected BigInteger end;
            @XmlAttribute(name = "primaryBegin")
            protected BigInteger primaryBegin;
            @XmlAttribute(name = "primaryEnd")
            protected BigInteger primaryEnd;
            @XmlAttribute(name = "accession", required = true)
            protected String accession;
            @XmlAttribute(name = "version", required = true)
            protected BigInteger version;
            @XmlAttribute(name = "complement")
            protected Boolean complement;

            public BigInteger getBegin() {
                return begin;
            }

            public void setBegin(BigInteger value) {
                this.begin = value;
            }

            public BigInteger getEnd() {
                return end;
            }

            public void setEnd(BigInteger value) {
                this.end = value;
            }

            public BigInteger getPrimaryBegin() {
                return primaryBegin;
            }

            public void setPrimaryBegin(BigInteger value) {
                this.primaryBegin = value;
            }

            public BigInteger getPrimaryEnd() {
                return primaryEnd;
            }

            public void setPrimaryEnd(BigInteger value) {
                this.primaryEnd = value;
            }

            public String getAccession() {
                return accession;
            }

            public void setAccession(String value) {
                this.accession = value;
            }

            public BigInteger getVersion() {
                return version;
            }

            public void setVersion(BigInteger value) {
                this.version = value;
            }

            public boolean isComplement() {
                if (complement == null) {
                    return false;
                } else {
                    return complement;
                }
            }

            public void setComplement(Boolean value) {
                this.complement = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxon",
        "xreves",
        "qualifiers"
    })
    public static class FeatureImpl
        implements Entry.Feature
    {

        @XmlElement(type = EntryImpl.FeatureImpl.TaxonImpl.class)
        protected EntryImpl.FeatureImpl.TaxonImpl taxon;
        @XmlElement(name = "xref", type = XrefTypeImpl.class)
        protected List<XrefType> xreves;
        @XmlElement(name = "qualifier", type = EntryImpl.FeatureImpl.QualifierImpl.class)
        protected List<Entry.Feature.Qualifier> qualifiers;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "location", required = true)
        protected String location;

        public Entry.Feature.Taxon getTaxon() {
            return taxon;
        }

        public void setTaxon(Entry.Feature.Taxon value) {
            this.taxon = ((EntryImpl.FeatureImpl.TaxonImpl) value);
        }

        public List<XrefType> getXreves() {
            if (xreves == null) {
                xreves = new ArrayList<XrefType>();
            }
            return this.xreves;
        }

        public List<Entry.Feature.Qualifier> getQualifiers() {
            if (qualifiers == null) {
                qualifiers = new ArrayList<Entry.Feature.Qualifier>();
            }
            return this.qualifiers;
        }

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        public String getLocation() {
            return location;
        }

        public void setLocation(String value) {
            this.location = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class QualifierImpl
            implements Entry.Feature.Qualifier
        {

            protected String value;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getName() {
                return name;
            }

            public void setName(String value) {
                this.name = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lineage"
        })
        public static class TaxonImpl
            implements Entry.Feature.Taxon
        {

            @XmlElement(type = EntryImpl.FeatureImpl.TaxonImpl.LineageImpl.class)
            protected EntryImpl.FeatureImpl.TaxonImpl.LineageImpl lineage;
            @XmlAttribute(name = "scientificName", required = true)
            protected String scientificName;
            @XmlAttribute(name = "commonName")
            protected String commonName;
            @XmlAttribute(name = "taxId")
            protected BigInteger taxId;

            public Entry.Feature.Taxon.Lineage getLineage() {
                return lineage;
            }

            public void setLineage(Entry.Feature.Taxon.Lineage value) {
                this.lineage = ((EntryImpl.FeatureImpl.TaxonImpl.LineageImpl) value);
            }

            public String getScientificName() {
                return scientificName;
            }

            public void setScientificName(String value) {
                this.scientificName = value;
            }

            public String getCommonName() {
                return commonName;
            }

            public void setCommonName(String value) {
                this.commonName = value;
            }

            public BigInteger getTaxId() {
                return taxId;
            }

            public void setTaxId(BigInteger value) {
                this.taxId = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "taxons2"
            })
            public static class LineageImpl
                implements Entry.Feature.Taxon.Lineage
            {

                @XmlElement(name = "taxon", required = true, type = Taxon2Impl.class)
                protected List<Taxon2> taxons2;

                public List<Taxon2> getTaxons2() {
                    if (taxons2 == null) {
                        taxons2 = new ArrayList<Taxon2>();
                    }
                    return this.taxons2;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Taxon2Impl
                    implements Taxon2
                {

                    @XmlAttribute(name = "scientificName", required = true)
                    protected String scientificName;

                    public String getScientificName() {
                        return scientificName;
                    }

                    public void setScientificName(String value) {
                        this.scientificName = value;
                    }

                }

            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "authors",
        "applicants",
        "consortium",
        "submissionDate",
        "journal",
        "year",
        "volume",
        "issue",
        "firstPage",
        "lastPage",
        "comment",
        "referenceLocation",
        "xreves"
    })
    public static class ReferenceImpl
        implements Entry.Reference
    {

        protected String title;
        @XmlElement(name = "author")
        protected List<String> authors;
        @XmlElement(name = "applicant")
        protected List<String> applicants;
        protected String consortium;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar submissionDate;
        protected String journal;
        protected String year;
        protected String volume;
        protected String issue;
        protected String firstPage;
        protected String lastPage;
        protected String comment;
        protected String referenceLocation;
        @XmlElement(name = "xref", type = XrefTypeImpl.class)
        protected List<XrefType> xreves;
        @XmlAttribute(name = "type", required = true)
        protected String type;
        @XmlAttribute(name = "number", required = true)
        protected BigInteger number;
        @XmlAttribute(name = "location")
        protected String location;

        public String getTitle() {
            return title;
        }

        public void setTitle(String value) {
            this.title = value;
        }

        public List<String> getAuthors() {
            if (authors == null) {
                authors = new ArrayList<String>();
            }
            return this.authors;
        }

        public List<String> getApplicants() {
            if (applicants == null) {
                applicants = new ArrayList<String>();
            }
            return this.applicants;
        }

        public String getConsortium() {
            return consortium;
        }

        public void setConsortium(String value) {
            this.consortium = value;
        }

        public XMLGregorianCalendar getSubmissionDate() {
            return submissionDate;
        }

        public void setSubmissionDate(XMLGregorianCalendar value) {
            this.submissionDate = value;
        }

        public String getJournal() {
            return journal;
        }

        public void setJournal(String value) {
            this.journal = value;
        }

        public String getYear() {
            return year;
        }

        public void setYear(String value) {
            this.year = value;
        }

        public String getVolume() {
            return volume;
        }

        public void setVolume(String value) {
            this.volume = value;
        }

        public String getIssue() {
            return issue;
        }

        public void setIssue(String value) {
            this.issue = value;
        }

        public String getFirstPage() {
            return firstPage;
        }

        public void setFirstPage(String value) {
            this.firstPage = value;
        }

        public String getLastPage() {
            return lastPage;
        }

        public void setLastPage(String value) {
            this.lastPage = value;
        }

        public String getComment() {
            return comment;
        }

        public void setComment(String value) {
            this.comment = value;
        }

        public String getReferenceLocation() {
            return referenceLocation;
        }

        public void setReferenceLocation(String value) {
            this.referenceLocation = value;
        }

        public List<XrefType> getXreves() {
            if (xreves == null) {
                xreves = new ArrayList<XrefType>();
            }
            return this.xreves;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

        public BigInteger getNumber() {
            return number;
        }

        public void setNumber(BigInteger value) {
            this.number = value;
        }

        public String getLocation() {
            return location;
        }

        public void setLocation(String value) {
            this.location = value;
        }

    }

}
