//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl;

import javax.xml.bind.annotation.XmlRegistry;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ANALYSIS;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ANALYSISSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.AnalysisFileType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.AttributeType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ChildTaxonType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.EXPERIMENT;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.EXPERIMENTSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Entry;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.EntrySet;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.EntrySetType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.IdentifierType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.LibraryDescriptorType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.LibraryType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.LinkType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.NameType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.OrganismType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PROJECT;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PROJECTSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ParentTaxonType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PipelineType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PlatformType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PoolMemberType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ProcessingType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.PublicationType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.QualifiedNameType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ROOT;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.RUN;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.RUNSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ReferenceAssemblyType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ReferenceSequenceType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SAMPLE;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SAMPLESET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.STUDY;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.STUDYSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SUBMISSION;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SUBMISSIONSET;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SampleDescriptorType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SequencingDirectivesType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.SpotDescriptorType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.TaxonSet;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.TaxonSetType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.URLType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.XRefType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.XrefType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PROJECT }
     * 
     */
    public PROJECTImpl createPROJECT() {
        return new PROJECTImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS }
     * 
     */
    public ANALYSISImpl createANALYSIS() {
        return new ANALYSISImpl();
    }

    /**
     * Create an instance of {@link RUN }
     * 
     */
    public RUNImpl createRUN() {
        return new RUNImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION }
     * 
     */
    public SUBMISSIONImpl createSUBMISSION() {
        return new SUBMISSIONImpl();
    }

    /**
     * Create an instance of {@link EXPERIMENT }
     * 
     */
    public EXPERIMENTImpl createEXPERIMENT() {
        return new EXPERIMENTImpl();
    }

    /**
     * Create an instance of {@link STUDY }
     * 
     */
    public STUDYImpl createSTUDY() {
        return new STUDYImpl();
    }

    /**
     * Create an instance of {@link SAMPLE }
     * 
     */
    public SAMPLEImpl createSAMPLE() {
        return new SAMPLEImpl();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public EntryImpl createEntry() {
        return new EntryImpl();
    }

    /**
     * Create an instance of {@link uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Taxon }
     * 
     */
    public uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl createTaxon() {
        return new uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkTypeImpl createLinkType() {
        return new LinkTypeImpl();
    }

    /**
     * Create an instance of {@link PipelineType }
     * 
     */
    public PipelineTypeImpl createPipelineType() {
        return new PipelineTypeImpl();
    }

    /**
     * Create an instance of {@link ReferenceSequenceType }
     * 
     */
    public ReferenceSequenceTypeImpl createReferenceSequenceType() {
        return new ReferenceSequenceTypeImpl();
    }

    /**
     * Create an instance of {@link ReferenceAssemblyType }
     * 
     */
    public ReferenceAssemblyTypeImpl createReferenceAssemblyType() {
        return new ReferenceAssemblyTypeImpl();
    }

    /**
     * Create an instance of {@link ReferenceAssemblyType.CUSTOM }
     * 
     */
    public ReferenceAssemblyTypeImpl.CUSTOMImpl createReferenceAssemblyTypeCUSTOM() {
        return new ReferenceAssemblyTypeImpl.CUSTOMImpl();
    }

    /**
     * Create an instance of {@link SampleDescriptorType }
     * 
     */
    public SampleDescriptorTypeImpl createSampleDescriptorType() {
        return new SampleDescriptorTypeImpl();
    }

    /**
     * Create an instance of {@link ChildTaxonType }
     * 
     */
    public ChildTaxonTypeImpl createChildTaxonType() {
        return new ChildTaxonTypeImpl();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationTypeImpl createPublicationType() {
        return new PublicationTypeImpl();
    }

    /**
     * Create an instance of {@link PublicationType.PUBLICATIONLINKS }
     * 
     */
    public PublicationTypeImpl.PUBLICATIONLINKSImpl createPublicationTypePUBLICATIONLINKS() {
        return new PublicationTypeImpl.PUBLICATIONLINKSImpl();
    }

    /**
     * Create an instance of {@link PublicationType.STRUCTUREDCITATION }
     * 
     */
    public PublicationTypeImpl.STRUCTUREDCITATIONImpl createPublicationTypeSTRUCTUREDCITATION() {
        return new PublicationTypeImpl.STRUCTUREDCITATIONImpl();
    }

    /**
     * Create an instance of {@link ParentTaxonType }
     * 
     */
    public ParentTaxonTypeImpl createParentTaxonType() {
        return new ParentTaxonTypeImpl();
    }

    /**
     * Create an instance of {@link PoolMemberType }
     * 
     */
    public PoolMemberTypeImpl createPoolMemberType() {
        return new PoolMemberTypeImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType }
     * 
     */
    public LibraryDescriptorTypeImpl createLibraryDescriptorType() {
        return new LibraryDescriptorTypeImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.TARGETEDLOCI }
     * 
     */
    public LibraryDescriptorTypeImpl.TARGETEDLOCIImpl createLibraryDescriptorTypeTARGETEDLOCI() {
        return new LibraryDescriptorTypeImpl.TARGETEDLOCIImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT }
     * 
     */
    public LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl createLibraryDescriptorTypeLIBRARYLAYOUT() {
        return new LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl();
    }

    /**
     * Create an instance of {@link Entry.Contig }
     * 
     */
    public EntryImpl.ContigImpl createEntryContig() {
        return new EntryImpl.ContigImpl();
    }

    /**
     * Create an instance of {@link Entry.Assembly }
     * 
     */
    public EntryImpl.AssemblyImpl createEntryAssembly() {
        return new EntryImpl.AssemblyImpl();
    }

    /**
     * Create an instance of {@link Entry.Feature }
     * 
     */
    public EntryImpl.FeatureImpl createEntryFeature() {
        return new EntryImpl.FeatureImpl();
    }

    /**
     * Create an instance of {@link Entry.Feature.Taxon }
     * 
     */
    public EntryImpl.FeatureImpl.TaxonImpl createEntryFeatureTaxon() {
        return new EntryImpl.FeatureImpl.TaxonImpl();
    }

    /**
     * Create an instance of {@link Entry.Feature.Taxon.Lineage }
     * 
     */
    public EntryImpl.FeatureImpl.TaxonImpl.LineageImpl createEntryFeatureTaxonLineage() {
        return new EntryImpl.FeatureImpl.TaxonImpl.LineageImpl();
    }

    /**
     * Create an instance of {@link STUDY.DESCRIPTOR }
     * 
     */
    public STUDYImpl.DESCRIPTORImpl createSTUDYDESCRIPTOR() {
        return new STUDYImpl.DESCRIPTORImpl();
    }

    /**
     * Create an instance of {@link STUDY.DESCRIPTOR.RELATEDSTUDIES }
     * 
     */
    public STUDYImpl.DESCRIPTORImpl.RELATEDSTUDIESImpl createSTUDYDESCRIPTORRELATEDSTUDIES() {
        return new STUDYImpl.DESCRIPTORImpl.RELATEDSTUDIESImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl createSUBMISSIONACTIONS() {
        return new SUBMISSIONImpl.ACTIONSImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl createSUBMISSIONACTIONSACTION() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.CONTACTS }
     * 
     */
    public SUBMISSIONImpl.CONTACTSImpl createSUBMISSIONCONTACTS() {
        return new SUBMISSIONImpl.CONTACTSImpl();
    }

    /**
     * Create an instance of {@link RUN.DATABLOCK }
     * 
     */
    public RUNImpl.DATABLOCKImpl createRUNDATABLOCK() {
        return new RUNImpl.DATABLOCKImpl();
    }

    /**
     * Create an instance of {@link RUN.DATABLOCK.FILES }
     * 
     */
    public RUNImpl.DATABLOCKImpl.FILESImpl createRUNDATABLOCKFILES() {
        return new RUNImpl.DATABLOCKImpl.FILESImpl();
    }

    /**
     * Create an instance of {@link PlatformType }
     * 
     */
    public PlatformTypeImpl createPlatformType() {
        return new PlatformTypeImpl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType }
     * 
     */
    public SpotDescriptorTypeImpl createSpotDescriptorType() {
        return new SpotDescriptorTypeImpl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC }
     * 
     */
    public SpotDescriptorTypeImpl.SPOTDECODESPECImpl createSpotDescriptorTypeSPOTDECODESPEC() {
        return new SpotDescriptorTypeImpl.SPOTDECODESPECImpl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC }
     * 
     */
    public SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl createSpotDescriptorTypeSPOTDECODESPECREADSPEC() {
        return new SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE }
     * 
     */
    public SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.EXPECTEDBASECALLTABLEImpl createSpotDescriptorTypeSPOTDECODESPECREADSPECEXPECTEDBASECALLTABLE() {
        return new SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.EXPECTEDBASECALLTABLEImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISTYPE }
     * 
     */
    public ANALYSISImpl.ANALYSISTYPEImpl createANALYSISANALYSISTYPE() {
        return new ANALYSISImpl.ANALYSISTYPEImpl();
    }

    /**
     * Create an instance of {@link PROJECT.PROJECTLINKS }
     * 
     */
    public PROJECTImpl.PROJECTLINKSImpl createPROJECTPROJECTLINKS() {
        return new PROJECTImpl.PROJECTLINKSImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDCHROMOSOMES }
     * 
     */
    public PROJECTImpl.RELATEDCHROMOSOMESImpl createPROJECTRELATEDCHROMOSOMES() {
        return new PROJECTImpl.RELATEDCHROMOSOMESImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDPROJECTS }
     * 
     */
    public PROJECTImpl.RELATEDPROJECTSImpl createPROJECTRELATEDPROJECTS() {
        return new PROJECTImpl.RELATEDPROJECTSImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDPROJECTS.RELATEDPROJECT }
     * 
     */
    public PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl createPROJECTRELATEDPROJECTSRELATEDPROJECT() {
        return new PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl();
    }

    /**
     * Create an instance of {@link PROJECT.SUBMISSIONPROJECT }
     * 
     */
    public PROJECTImpl.SUBMISSIONPROJECTImpl createPROJECTSUBMISSIONPROJECT() {
        return new PROJECTImpl.SUBMISSIONPROJECTImpl();
    }

    /**
     * Create an instance of {@link TaxonSet }
     * 
     */
    public TaxonSetImpl createTaxonSet() {
        return new TaxonSetImpl();
    }

    /**
     * Create an instance of {@link ANALYSISSET }
     * 
     */
    public ANALYSISSETImpl createANALYSISSET() {
        return new ANALYSISSETImpl();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierTypeImpl createIdentifierType() {
        return new IdentifierTypeImpl();
    }

    /**
     * Create an instance of {@link PROJECT.PUBLICATIONS }
     * 
     */
    public PROJECTImpl.PUBLICATIONSImpl createPROJECTPUBLICATIONS() {
        return new PROJECTImpl.PUBLICATIONSImpl();
    }

    /**
     * Create an instance of {@link PROJECT.COLLABORATORS }
     * 
     */
    public PROJECTImpl.COLLABORATORSImpl createPROJECTCOLLABORATORS() {
        return new PROJECTImpl.COLLABORATORSImpl();
    }

    /**
     * Create an instance of {@link PROJECT.UMBRELLAPROJECT }
     * 
     */
    public PROJECTImpl.UMBRELLAPROJECTImpl createPROJECTUMBRELLAPROJECT() {
        return new PROJECTImpl.UMBRELLAPROJECTImpl();
    }

    /**
     * Create an instance of {@link PROJECT.PROJECTATTRIBUTES }
     * 
     */
    public PROJECTImpl.PROJECTATTRIBUTESImpl createPROJECTPROJECTATTRIBUTES() {
        return new PROJECTImpl.PROJECTATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link ROOT }
     * 
     */
    public ROOTImpl createROOT() {
        return new ROOTImpl();
    }

    /**
     * Create an instance of {@link EXPERIMENTSET }
     * 
     */
    public EXPERIMENTSETImpl createEXPERIMENTSET() {
        return new EXPERIMENTSETImpl();
    }

    /**
     * Create an instance of {@link RUNSET }
     * 
     */
    public RUNSETImpl createRUNSET() {
        return new RUNSETImpl();
    }

    /**
     * Create an instance of {@link STUDYSET }
     * 
     */
    public STUDYSETImpl createSTUDYSET() {
        return new STUDYSETImpl();
    }

    /**
     * Create an instance of {@link SAMPLESET }
     * 
     */
    public SAMPLESETImpl createSAMPLESET() {
        return new SAMPLESETImpl();
    }

    /**
     * Create an instance of {@link SUBMISSIONSET }
     * 
     */
    public SUBMISSIONSETImpl createSUBMISSIONSET() {
        return new SUBMISSIONSETImpl();
    }

    /**
     * Create an instance of {@link EntrySetType }
     * 
     */
    public EntrySetTypeImpl createEntrySetType() {
        return new EntrySetTypeImpl();
    }

    /**
     * Create an instance of {@link TaxonSetType }
     * 
     */
    public TaxonSetTypeImpl createTaxonSetType() {
        return new TaxonSetTypeImpl();
    }

    /**
     * Create an instance of {@link PROJECTSET }
     * 
     */
    public PROJECTSETImpl createPROJECTSET() {
        return new PROJECTSETImpl();
    }

    /**
     * Create an instance of {@link EntrySet }
     * 
     */
    public EntrySetImpl createEntrySet() {
        return new EntrySetImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.STUDYREF }
     * 
     */
    public ANALYSISImpl.STUDYREFImpl createANALYSISSTUDYREF() {
        return new ANALYSISImpl.STUDYREFImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.SAMPLEREF }
     * 
     */
    public ANALYSISImpl.SAMPLEREFImpl createANALYSISSAMPLEREF() {
        return new ANALYSISImpl.SAMPLEREFImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.EXPERIMENTREF }
     * 
     */
    public ANALYSISImpl.EXPERIMENTREFImpl createANALYSISEXPERIMENTREF() {
        return new ANALYSISImpl.EXPERIMENTREFImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.RUNREF }
     * 
     */
    public ANALYSISImpl.RUNREFImpl createANALYSISRUNREF() {
        return new ANALYSISImpl.RUNREFImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISREF }
     * 
     */
    public ANALYSISImpl.ANALYSISREFImpl createANALYSISANALYSISREF() {
        return new ANALYSISImpl.ANALYSISREFImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.FILES }
     * 
     */
    public ANALYSISImpl.FILESImpl createANALYSISFILES() {
        return new ANALYSISImpl.FILESImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISLINKS }
     * 
     */
    public ANALYSISImpl.ANALYSISLINKSImpl createANALYSISANALYSISLINKS() {
        return new ANALYSISImpl.ANALYSISLINKSImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISATTRIBUTES }
     * 
     */
    public ANALYSISImpl.ANALYSISATTRIBUTESImpl createANALYSISANALYSISATTRIBUTES() {
        return new ANALYSISImpl.ANALYSISATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link RUN.EXPERIMENTREF }
     * 
     */
    public RUNImpl.EXPERIMENTREFImpl createRUNEXPERIMENTREF() {
        return new RUNImpl.EXPERIMENTREFImpl();
    }

    /**
     * Create an instance of {@link ProcessingType }
     * 
     */
    public ProcessingTypeImpl createProcessingType() {
        return new ProcessingTypeImpl();
    }

    /**
     * Create an instance of {@link RUN.RUNTYPE }
     * 
     */
    public RUNImpl.RUNTYPEImpl createRUNRUNTYPE() {
        return new RUNImpl.RUNTYPEImpl();
    }

    /**
     * Create an instance of {@link RUN.RUNLINKS }
     * 
     */
    public RUNImpl.RUNLINKSImpl createRUNRUNLINKS() {
        return new RUNImpl.RUNLINKSImpl();
    }

    /**
     * Create an instance of {@link RUN.RUNATTRIBUTES }
     * 
     */
    public RUNImpl.RUNATTRIBUTESImpl createRUNRUNATTRIBUTES() {
        return new RUNImpl.RUNATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.SUBMISSIONLINKS }
     * 
     */
    public SUBMISSIONImpl.SUBMISSIONLINKSImpl createSUBMISSIONSUBMISSIONLINKS() {
        return new SUBMISSIONImpl.SUBMISSIONLINKSImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.SUBMISSIONATTRIBUTES }
     * 
     */
    public SUBMISSIONImpl.SUBMISSIONATTRIBUTESImpl createSUBMISSIONSUBMISSIONATTRIBUTES() {
        return new SUBMISSIONImpl.SUBMISSIONATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link EXPERIMENT.STUDYREF }
     * 
     */
    public EXPERIMENTImpl.STUDYREFImpl createEXPERIMENTSTUDYREF() {
        return new EXPERIMENTImpl.STUDYREFImpl();
    }

    /**
     * Create an instance of {@link LibraryType }
     * 
     */
    public LibraryTypeImpl createLibraryType() {
        return new LibraryTypeImpl();
    }

    /**
     * Create an instance of {@link EXPERIMENT.EXPERIMENTLINKS }
     * 
     */
    public EXPERIMENTImpl.EXPERIMENTLINKSImpl createEXPERIMENTEXPERIMENTLINKS() {
        return new EXPERIMENTImpl.EXPERIMENTLINKSImpl();
    }

    /**
     * Create an instance of {@link EXPERIMENT.EXPERIMENTATTRIBUTES }
     * 
     */
    public EXPERIMENTImpl.EXPERIMENTATTRIBUTESImpl createEXPERIMENTEXPERIMENTATTRIBUTES() {
        return new EXPERIMENTImpl.EXPERIMENTATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link STUDY.STUDYLINKS }
     * 
     */
    public STUDYImpl.STUDYLINKSImpl createSTUDYSTUDYLINKS() {
        return new STUDYImpl.STUDYLINKSImpl();
    }

    /**
     * Create an instance of {@link STUDY.STUDYATTRIBUTES }
     * 
     */
    public STUDYImpl.STUDYATTRIBUTESImpl createSTUDYSTUDYATTRIBUTES() {
        return new STUDYImpl.STUDYATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link SAMPLE.SAMPLENAME }
     * 
     */
    public SAMPLEImpl.SAMPLENAMEImpl createSAMPLESAMPLENAME() {
        return new SAMPLEImpl.SAMPLENAMEImpl();
    }

    /**
     * Create an instance of {@link SAMPLE.SAMPLELINKS }
     * 
     */
    public SAMPLEImpl.SAMPLELINKSImpl createSAMPLESAMPLELINKS() {
        return new SAMPLEImpl.SAMPLELINKSImpl();
    }

    /**
     * Create an instance of {@link SAMPLE.SAMPLEATTRIBUTES }
     * 
     */
    public SAMPLEImpl.SAMPLEATTRIBUTESImpl createSAMPLESAMPLEATTRIBUTES() {
        return new SAMPLEImpl.SAMPLEATTRIBUTESImpl();
    }

    /**
     * Create an instance of {@link Entry.Reference }
     * 
     */
    public EntryImpl.ReferenceImpl createEntryReference() {
        return new EntryImpl.ReferenceImpl();
    }

    /**
     * Create an instance of {@link XrefType }
     * 
     */
    public XrefTypeImpl createXrefType() {
        return new XrefTypeImpl();
    }

    /**
     * Create an instance of {@link uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Taxon.Lineage }
     * 
     */
    public uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.LineageImpl createTaxonLineage() {
        return new uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.LineageImpl();
    }

    /**
     * Create an instance of {@link uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Taxon.Children }
     * 
     */
    public uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.ChildrenImpl createTaxonChildren() {
        return new uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.ChildrenImpl();
    }

    /**
     * Create an instance of {@link uk.ac.ebi.literature.data_citation.ena.jaxb_beans.Taxon.Synonym }
     * 
     */
    public uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.SynonymImpl createTaxonSynonym() {
        return new uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.TaxonImpl.SynonymImpl();
    }

    /**
     * Create an instance of {@link AnalysisFileType }
     * 
     */
    public AnalysisFileTypeImpl createAnalysisFileType() {
        return new AnalysisFileTypeImpl();
    }

    /**
     * Create an instance of {@link OrganismType }
     * 
     */
    public OrganismTypeImpl createOrganismType() {
        return new OrganismTypeImpl();
    }

    /**
     * Create an instance of {@link SequencingDirectivesType }
     * 
     */
    public SequencingDirectivesTypeImpl createSequencingDirectivesType() {
        return new SequencingDirectivesTypeImpl();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameTypeImpl createNameType() {
        return new NameTypeImpl();
    }

    /**
     * Create an instance of {@link XRefType }
     * 
     */
    public XRefTypeImpl createXRefType() {
        return new XRefTypeImpl();
    }

    /**
     * Create an instance of {@link QualifiedNameType }
     * 
     */
    public QualifiedNameTypeImpl createQualifiedNameType() {
        return new QualifiedNameTypeImpl();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeTypeImpl createAttributeType() {
        return new AttributeTypeImpl();
    }

    /**
     * Create an instance of {@link URLType }
     * 
     */
    public URLTypeImpl createURLType() {
        return new URLTypeImpl();
    }

    /**
     * Create an instance of {@link LinkType.ENTREZLINK }
     * 
     */
    public LinkTypeImpl.ENTREZLINKImpl createLinkTypeENTREZLINK() {
        return new LinkTypeImpl.ENTREZLINKImpl();
    }

    /**
     * Create an instance of {@link LinkType.URLLINK }
     * 
     */
    public LinkTypeImpl.URLLINKImpl createLinkTypeURLLINK() {
        return new LinkTypeImpl.URLLINKImpl();
    }

    /**
     * Create an instance of {@link PipelineType.PIPESECTION }
     * 
     */
    public PipelineTypeImpl.PIPESECTIONImpl createPipelineTypePIPESECTION() {
        return new PipelineTypeImpl.PIPESECTIONImpl();
    }

    /**
     * Create an instance of {@link ReferenceSequenceType.SEQUENCE }
     * 
     */
    public ReferenceSequenceTypeImpl.SEQUENCEImpl createReferenceSequenceTypeSEQUENCE() {
        return new ReferenceSequenceTypeImpl.SEQUENCEImpl();
    }

    /**
     * Create an instance of {@link ReferenceAssemblyType.STANDARD }
     * 
     */
    public ReferenceAssemblyTypeImpl.STANDARDImpl createReferenceAssemblyTypeSTANDARD() {
        return new ReferenceAssemblyTypeImpl.STANDARDImpl();
    }

    /**
     * Create an instance of {@link ReferenceAssemblyType.CUSTOM.URLLINK }
     * 
     */
    public ReferenceAssemblyTypeImpl.CUSTOMImpl.URLLINKImpl createReferenceAssemblyTypeCUSTOMURLLINK() {
        return new ReferenceAssemblyTypeImpl.CUSTOMImpl.URLLINKImpl();
    }

    /**
     * Create an instance of {@link SampleDescriptorType.POOL }
     * 
     */
    public SampleDescriptorTypeImpl.POOLImpl createSampleDescriptorTypePOOL() {
        return new SampleDescriptorTypeImpl.POOLImpl();
    }

    /**
     * Create an instance of {@link ChildTaxonType.Children }
     * 
     */
    public ChildTaxonTypeImpl.ChildrenImpl createChildTaxonTypeChildren() {
        return new ChildTaxonTypeImpl.ChildrenImpl();
    }

    /**
     * Create an instance of {@link PublicationType.PUBLICATIONLINKS.PUBLICATIONLINK }
     * 
     */
    public PublicationTypeImpl.PUBLICATIONLINKSImpl.PUBLICATIONLINKImpl createPublicationTypePUBLICATIONLINKSPUBLICATIONLINK() {
        return new PublicationTypeImpl.PUBLICATIONLINKSImpl.PUBLICATIONLINKImpl();
    }

    /**
     * Create an instance of {@link PublicationType.STRUCTUREDCITATION.AUTHORS }
     * 
     */
    public PublicationTypeImpl.STRUCTUREDCITATIONImpl.AUTHORSImpl createPublicationTypeSTRUCTUREDCITATIONAUTHORS() {
        return new PublicationTypeImpl.STRUCTUREDCITATIONImpl.AUTHORSImpl();
    }

    /**
     * Create an instance of {@link ParentTaxonType.Children }
     * 
     */
    public ParentTaxonTypeImpl.ChildrenImpl createParentTaxonTypeChildren() {
        return new ParentTaxonTypeImpl.ChildrenImpl();
    }

    /**
     * Create an instance of {@link PoolMemberType.READLABEL }
     * 
     */
    public PoolMemberTypeImpl.READLABELImpl createPoolMemberTypeREADLABEL() {
        return new PoolMemberTypeImpl.READLABELImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.TARGETEDLOCI.LOCUS }
     * 
     */
    public LibraryDescriptorTypeImpl.TARGETEDLOCIImpl.LOCUSImpl createLibraryDescriptorTypeTARGETEDLOCILOCUS() {
        return new LibraryDescriptorTypeImpl.TARGETEDLOCIImpl.LOCUSImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT.PAIRED }
     * 
     */
    public LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl.PAIREDImpl createLibraryDescriptorTypeLIBRARYLAYOUTPAIRED() {
        return new LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl.PAIREDImpl();
    }

    /**
     * Create an instance of {@link LibraryDescriptorType.LIBRARYLAYOUT.SINGLE }
     * 
     */
    public LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl.SINGLEImpl createLibraryDescriptorTypeLIBRARYLAYOUTSINGLE() {
        return new LibraryDescriptorTypeImpl.LIBRARYLAYOUTImpl.SINGLEImpl();
    }

    /**
     * Create an instance of {@link Entry.Contig.Range }
     * 
     */
    public EntryImpl.ContigImpl.RangeImpl createEntryContigRange() {
        return new EntryImpl.ContigImpl.RangeImpl();
    }

    /**
     * Create an instance of {@link Entry.Contig.Gap }
     * 
     */
    public EntryImpl.ContigImpl.GapImpl createEntryContigGap() {
        return new EntryImpl.ContigImpl.GapImpl();
    }

    /**
     * Create an instance of {@link Entry.Assembly.Range }
     * 
     */
    public EntryImpl.AssemblyImpl.RangeImpl createEntryAssemblyRange() {
        return new EntryImpl.AssemblyImpl.RangeImpl();
    }

    /**
     * Create an instance of {@link Entry.Feature.Qualifier }
     * 
     */
    public EntryImpl.FeatureImpl.QualifierImpl createEntryFeatureQualifier() {
        return new EntryImpl.FeatureImpl.QualifierImpl();
    }

    /**
     * Create an instance of {@link Entry.Feature.Taxon.Lineage.Taxon2 }
     * 
     */
    public EntryImpl.FeatureImpl.TaxonImpl.LineageImpl.Taxon2Impl createEntryFeatureTaxonLineageTaxon() {
        return new EntryImpl.FeatureImpl.TaxonImpl.LineageImpl.Taxon2Impl();
    }

    /**
     * Create an instance of {@link STUDY.DESCRIPTOR.STUDYTYPE }
     * 
     */
    public STUDYImpl.DESCRIPTORImpl.STUDYTYPEImpl createSTUDYDESCRIPTORSTUDYTYPE() {
        return new STUDYImpl.DESCRIPTORImpl.STUDYTYPEImpl();
    }

    /**
     * Create an instance of {@link STUDY.DESCRIPTOR.RELATEDSTUDIES.RELATEDSTUDY }
     * 
     */
    public STUDYImpl.DESCRIPTORImpl.RELATEDSTUDIESImpl.RELATEDSTUDYImpl createSTUDYDESCRIPTORRELATEDSTUDIESRELATEDSTUDY() {
        return new STUDYImpl.DESCRIPTORImpl.RELATEDSTUDIESImpl.RELATEDSTUDYImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.VALIDATE }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.VALIDATEImpl createSUBMISSIONACTIONSACTIONVALIDATE() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.VALIDATEImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.PROTECT }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.PROTECTImpl createSUBMISSIONACTIONSACTIONPROTECT() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.PROTECTImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.RELEASE }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.RELEASEImpl createSUBMISSIONACTIONSACTIONRELEASE() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.RELEASEImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.HOLD }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.HOLDImpl createSUBMISSIONACTIONSACTIONHOLD() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.HOLDImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.SUPPRESS }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.SUPPRESSImpl createSUBMISSIONACTIONSACTIONSUPPRESS() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.SUPPRESSImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.CANCEL }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.CANCELImpl createSUBMISSIONACTIONSACTIONCANCEL() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.CANCELImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.MODIFY }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.MODIFYImpl createSUBMISSIONACTIONSACTIONMODIFY() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.MODIFYImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.ACTIONS.ACTION.ADD }
     * 
     */
    public SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.ADDImpl createSUBMISSIONACTIONSACTIONADD() {
        return new SUBMISSIONImpl.ACTIONSImpl.ACTIONImpl.ADDImpl();
    }

    /**
     * Create an instance of {@link SUBMISSION.CONTACTS.CONTACT }
     * 
     */
    public SUBMISSIONImpl.CONTACTSImpl.CONTACTImpl createSUBMISSIONCONTACTSCONTACT() {
        return new SUBMISSIONImpl.CONTACTSImpl.CONTACTImpl();
    }

    /**
     * Create an instance of {@link RUN.DATABLOCK.FILES.FILE }
     * 
     */
    public RUNImpl.DATABLOCKImpl.FILESImpl.FILEImpl createRUNDATABLOCKFILESFILE() {
        return new RUNImpl.DATABLOCKImpl.FILESImpl.FILEImpl();
    }

    /**
     * Create an instance of {@link PlatformType.CAPILLARY }
     * 
     */
    public PlatformTypeImpl.CAPILLARYImpl createPlatformTypeCAPILLARY() {
        return new PlatformTypeImpl.CAPILLARYImpl();
    }

    /**
     * Create an instance of {@link PlatformType.IONTORRENT }
     * 
     */
    public PlatformTypeImpl.IONTORRENTImpl createPlatformTypeIONTORRENT() {
        return new PlatformTypeImpl.IONTORRENTImpl();
    }

    /**
     * Create an instance of {@link PlatformType.PACBIOSMRT }
     * 
     */
    public PlatformTypeImpl.PACBIOSMRTImpl createPlatformTypePACBIOSMRT() {
        return new PlatformTypeImpl.PACBIOSMRTImpl();
    }

    /**
     * Create an instance of {@link PlatformType.OXFORDNANOPORE }
     * 
     */
    public PlatformTypeImpl.OXFORDNANOPOREImpl createPlatformTypeOXFORDNANOPORE() {
        return new PlatformTypeImpl.OXFORDNANOPOREImpl();
    }

    /**
     * Create an instance of {@link PlatformType.COMPLETEGENOMICS }
     * 
     */
    public PlatformTypeImpl.COMPLETEGENOMICSImpl createPlatformTypeCOMPLETEGENOMICS() {
        return new PlatformTypeImpl.COMPLETEGENOMICSImpl();
    }

    /**
     * Create an instance of {@link PlatformType.ABISOLID }
     * 
     */
    public PlatformTypeImpl.ABISOLIDImpl createPlatformTypeABISOLID() {
        return new PlatformTypeImpl.ABISOLIDImpl();
    }

    /**
     * Create an instance of {@link PlatformType.HELICOS }
     * 
     */
    public PlatformTypeImpl.HELICOSImpl createPlatformTypeHELICOS() {
        return new PlatformTypeImpl.HELICOSImpl();
    }

    /**
     * Create an instance of {@link PlatformType.ILLUMINA }
     * 
     */
    public PlatformTypeImpl.ILLUMINAImpl createPlatformTypeILLUMINA() {
        return new PlatformTypeImpl.ILLUMINAImpl();
    }

    /**
     * Create an instance of {@link PlatformType.LS454 }
     * 
     */
    public PlatformTypeImpl.LS454Impl createPlatformTypeLS454() {
        return new PlatformTypeImpl.LS454Impl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.RELATIVEORDER }
     * 
     */
    public SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.RELATIVEORDERImpl createSpotDescriptorTypeSPOTDECODESPECREADSPECRELATIVEORDER() {
        return new SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.RELATIVEORDERImpl();
    }

    /**
     * Create an instance of {@link SpotDescriptorType.SPOTDECODESPEC.READSPEC.EXPECTEDBASECALLTABLE.BASECALL }
     * 
     */
    public SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.EXPECTEDBASECALLTABLEImpl.BASECALLImpl createSpotDescriptorTypeSPOTDECODESPECREADSPECEXPECTEDBASECALLTABLEBASECALL() {
        return new SpotDescriptorTypeImpl.SPOTDECODESPECImpl.READSPECImpl.EXPECTEDBASECALLTABLEImpl.BASECALLImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISTYPE.SAMPLEPHENOTYPE }
     * 
     */
    public ANALYSISImpl.ANALYSISTYPEImpl.SAMPLEPHENOTYPEImpl createANALYSISANALYSISTYPESAMPLEPHENOTYPE() {
        return new ANALYSISImpl.ANALYSISTYPEImpl.SAMPLEPHENOTYPEImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISTYPE.SEQUENCEANNOTATION }
     * 
     */
    public ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEANNOTATIONImpl createANALYSISANALYSISTYPESEQUENCEANNOTATION() {
        return new ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEANNOTATIONImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISTYPE.SEQUENCEASSEMBLY }
     * 
     */
    public ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEASSEMBLYImpl createANALYSISANALYSISTYPESEQUENCEASSEMBLY() {
        return new ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEASSEMBLYImpl();
    }

    /**
     * Create an instance of {@link ANALYSIS.ANALYSISTYPE.SEQUENCEVARIATION }
     * 
     */
    public ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEVARIATIONImpl createANALYSISANALYSISTYPESEQUENCEVARIATION() {
        return new ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEVARIATIONImpl();
    }

    /**
     * Create an instance of {@link PROJECT.PROJECTLINKS.PROJECTLINK }
     * 
     */
    public PROJECTImpl.PROJECTLINKSImpl.PROJECTLINKImpl createPROJECTPROJECTLINKSPROJECTLINK() {
        return new PROJECTImpl.PROJECTLINKSImpl.PROJECTLINKImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDCHROMOSOMES.RELATEDCHROMOSOME }
     * 
     */
    public PROJECTImpl.RELATEDCHROMOSOMESImpl.RELATEDCHROMOSOMEImpl createPROJECTRELATEDCHROMOSOMESRELATEDCHROMOSOME() {
        return new PROJECTImpl.RELATEDCHROMOSOMESImpl.RELATEDCHROMOSOMEImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDPROJECTS.RELATEDPROJECT.PEERPROJECT }
     * 
     */
    public PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.PEERPROJECTImpl createPROJECTRELATEDPROJECTSRELATEDPROJECTPEERPROJECT() {
        return new PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.PEERPROJECTImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDPROJECTS.RELATEDPROJECT.CHILDPROJECT }
     * 
     */
    public PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.CHILDPROJECTImpl createPROJECTRELATEDPROJECTSRELATEDPROJECTCHILDPROJECT() {
        return new PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.CHILDPROJECTImpl();
    }

    /**
     * Create an instance of {@link PROJECT.RELATEDPROJECTS.RELATEDPROJECT.PARENTPROJECT }
     * 
     */
    public PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.PARENTPROJECTImpl createPROJECTRELATEDPROJECTSRELATEDPROJECTPARENTPROJECT() {
        return new PROJECTImpl.RELATEDPROJECTSImpl.RELATEDPROJECTImpl.PARENTPROJECTImpl();
    }

    /**
     * Create an instance of {@link PROJECT.SUBMISSIONPROJECT.SEQUENCINGPROJECT }
     * 
     */
    public PROJECTImpl.SUBMISSIONPROJECTImpl.SEQUENCINGPROJECTImpl createPROJECTSUBMISSIONPROJECTSEQUENCINGPROJECT() {
        return new PROJECTImpl.SUBMISSIONPROJECTImpl.SEQUENCINGPROJECTImpl();
    }

}
