//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ChildTaxonType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ParentTaxonType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParentTaxonType", propOrder = {
    "children"
})
public class ParentTaxonTypeImpl
    implements ParentTaxonType
{

    @XmlElement(type = ParentTaxonTypeImpl.ChildrenImpl.class)
    protected ParentTaxonTypeImpl.ChildrenImpl children;
    @XmlAttribute(name = "scientificName", required = true)
    protected String scientificName;
    @XmlAttribute(name = "commonName")
    protected String commonName;
    @XmlAttribute(name = "taxId", required = true)
    protected BigInteger taxId;
    @XmlAttribute(name = "rank")
    protected String rank;
    @XmlAttribute(name = "hidden")
    protected Boolean hidden;

    public ParentTaxonType.Children getChildren() {
        return children;
    }

    public void setChildren(ParentTaxonType.Children value) {
        this.children = ((ParentTaxonTypeImpl.ChildrenImpl) value);
    }

    public String getScientificName() {
        return scientificName;
    }

    public void setScientificName(String value) {
        this.scientificName = value;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String value) {
        this.commonName = value;
    }

    public BigInteger getTaxId() {
        return taxId;
    }

    public void setTaxId(BigInteger value) {
        this.taxId = value;
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String value) {
        this.rank = value;
    }

    public boolean isHidden() {
        if (hidden == null) {
            return false;
        } else {
            return hidden;
        }
    }

    public void setHidden(Boolean value) {
        this.hidden = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxons"
    })
    public static class ChildrenImpl
        implements ParentTaxonType.Children
    {

        @XmlElement(name = "taxon", required = true, type = ChildTaxonTypeImpl.class)
        protected List<ChildTaxonType> taxons;

        public List<ChildTaxonType> getTaxons() {
            if (taxons == null) {
                taxons = new ArrayList<ChildTaxonType>();
            }
            return this.taxons;
        }

    }

}
