//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ReferenceAssemblyType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceAssemblyType", namespace = "SRA.common", propOrder = {
    "custom",
    "standard"
})
public class ReferenceAssemblyTypeImpl
    implements ReferenceAssemblyType
{

    @XmlElement(name = "CUSTOM", type = ReferenceAssemblyTypeImpl.CUSTOMImpl.class)
    protected ReferenceAssemblyTypeImpl.CUSTOMImpl custom;
    @XmlElement(name = "STANDARD", type = ReferenceAssemblyTypeImpl.STANDARDImpl.class)
    protected ReferenceAssemblyTypeImpl.STANDARDImpl standard;

    public ReferenceAssemblyType.CUSTOM getCUSTOM() {
        return custom;
    }

    public void setCUSTOM(ReferenceAssemblyType.CUSTOM value) {
        this.custom = ((ReferenceAssemblyTypeImpl.CUSTOMImpl) value);
    }

    public ReferenceAssemblyType.STANDARD getSTANDARD() {
        return standard;
    }

    public void setSTANDARD(ReferenceAssemblyType.STANDARD value) {
        this.standard = ((ReferenceAssemblyTypeImpl.STANDARDImpl) value);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "urllinks"
    })
    public static class CUSTOMImpl
        implements ReferenceAssemblyType.CUSTOM
    {

        @XmlElement(name = "DESCRIPTION")
        protected String description;
        @XmlElement(name = "URL_LINK", required = true, type = ReferenceAssemblyTypeImpl.CUSTOMImpl.URLLINKImpl.class)
        protected List<ReferenceAssemblyType.CUSTOM.URLLINK> urllinks;

        public String getDESCRIPTION() {
            return description;
        }

        public void setDESCRIPTION(String value) {
            this.description = value;
        }

        public List<ReferenceAssemblyType.CUSTOM.URLLINK> getURLLINKS() {
            if (urllinks == null) {
                urllinks = new ArrayList<ReferenceAssemblyType.CUSTOM.URLLINK>();
            }
            return this.urllinks;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class URLLINKImpl
            implements ReferenceAssemblyType.CUSTOM.URLLINK
        {

            @XmlElement(name = "LABEL")
            protected String label;
            @XmlElement(name = "URL", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String url;

            public String getLABEL() {
                return label;
            }

            public void setLABEL(String value) {
                this.label = value;
            }

            public String getURL() {
                return url;
            }

            public void setURL(String value) {
                this.url = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class STANDARDImpl
        implements ReferenceAssemblyType.STANDARD
    {

        @XmlAttribute(name = "refname")
        protected String refname;
        @XmlAttribute(name = "accession")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String accession;

        public String getRefname() {
            return refname;
        }

        public void setRefname(String value) {
            this.refname = value;
        }

        public String getAccession() {
            return accession;
        }

        public void setAccession(String value) {
            this.accession = value;
        }

    }

}
