//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.09 at 05:04:58 PM BST 
//


package uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ReferenceAssemblyType;
import uk.ac.ebi.literature.data_citation.ena.jaxb_beans.ReferenceSequenceType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceSequenceType", namespace = "SRA.common", propOrder = {
    "assembly",
    "sequences"
})
@XmlSeeAlso({
    uk.ac.ebi.literature.data_citation.ena.jaxb_beans.impl.ANALYSISImpl.ANALYSISTYPEImpl.SEQUENCEVARIATIONImpl.class
})
public class ReferenceSequenceTypeImpl
    implements ReferenceSequenceType
{

    @XmlElement(name = "ASSEMBLY", type = ReferenceAssemblyTypeImpl.class)
    protected ReferenceAssemblyTypeImpl assembly;
    @XmlElement(name = "SEQUENCE", type = ReferenceSequenceTypeImpl.SEQUENCEImpl.class)
    protected List<ReferenceSequenceType.SEQUENCE> sequences;

    public ReferenceAssemblyType getASSEMBLY() {
        return assembly;
    }

    public void setASSEMBLY(ReferenceAssemblyType value) {
        this.assembly = ((ReferenceAssemblyTypeImpl) value);
    }

    public List<ReferenceSequenceType.SEQUENCE> getSEQUENCES() {
        if (sequences == null) {
            sequences = new ArrayList<ReferenceSequenceType.SEQUENCE>();
        }
        return this.sequences;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SEQUENCEImpl
        implements ReferenceSequenceType.SEQUENCE
    {

        @XmlAttribute(name = "refname")
        protected String refname;
        @XmlAttribute(name = "accession")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String accession;
        @XmlAttribute(name = "label")
        protected String label;

        public String getRefname() {
            return refname;
        }

        public void setRefname(String value) {
            this.refname = value;
        }

        public String getAccession() {
            return accession;
        }

        public void setAccession(String value) {
            this.accession = value;
        }

        public String getLabel() {
            return label;
        }

        public void setLabel(String value) {
            this.label = value;
        }

    }

}
